### ISSUE TITLE
QA Task for Display Main Menu

### ISSUE THREAD

**Issue by bchewy** [bchewy/eti_game#6]

**Comment by ghost** [comment]
test case updated to reflect the current state

**Comment by ghost** [comment]
@PoWeiXiang @twirle  The program crashes when invalid input of characters, special characters and when an empty input are entered. e.g. "abc", "!@#$". Don't think this is normal system behavior.

**Comment by ghost** [comment]
@PoWeiXiang @twirle I have 3 failures when I run my pytest.
1. When I select option1, my pytest fails with an raise IOError("reading from stdin while output is captured"
2. When option 4 is selected, it's not returning anything and it fails with an raise IOError("reading from stdin while output is captured"
3. When option 0 is selected, nothing is being returned

**Comment by PoWeiXiang** [comment]
> @PoWeiXiang @twirle I have 3 failures when I run my pytest.
> 
> 1. When I select option1, my pytest fails with an raise IOError("reading from stdin while output is captured"
> 2. When option 4 is selected, it's not returning anything and it fails with an raise IOError("reading from stdin while output is captured"
> 3. When option 0 is selected, nothing is being returned

@jiaweiii @twirle Point 2 and 3 is resolved.

**Comment by ghost** [comment]
@PoWeiXiang Thanks. Will try it out tmr and get back to you.

**Comment by twirle** [comment]
@jiaweiii Options 1 & 4 have been resolved by cutting in after the option has been selected.
Option 0 has been changed to return False, which will also stop the game thereafter.
